//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CustomsDeclarationProxy
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class cdiEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“cdiEntities”部分中的连接字符串初始化新 cdiEntities 对象。
        /// </summary>
        public cdiEntities() : base("name=cdiEntities", "cdiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 cdiEntities 对象。
        /// </summary>
        public cdiEntities(string connectionString) : base(connectionString, "cdiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 cdiEntities 对象。
        /// </summary>
        public cdiEntities(EntityConnection connection) : base(connection, "cdiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<decl_message> decl_message
        {
            get
            {
                if ((_decl_message == null))
                {
                    _decl_message = base.CreateObjectSet<decl_message>("decl_message");
                }
                return _decl_message;
            }
        }
        private ObjectSet<decl_message> _decl_message;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<resp_message> resp_message
        {
            get
            {
                if ((_resp_message == null))
                {
                    _resp_message = base.CreateObjectSet<resp_message>("resp_message");
                }
                return _resp_message;
            }
        }
        private ObjectSet<resp_message> _resp_message;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 decl_message EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTodecl_message(decl_message decl_message)
        {
            base.AddObject("decl_message", decl_message);
        }
    
        /// <summary>
        /// 用于向 resp_message EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToresp_message(resp_message resp_message)
        {
            base.AddObject("resp_message", resp_message);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cdiModel", Name="decl_message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class decl_message : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 decl_message 对象。
        /// </summary>
        /// <param name="decl_message_id">decl_message_id 属性的初始值。</param>
        public static decl_message Createdecl_message(global::System.Int64 decl_message_id)
        {
            decl_message decl_message = new decl_message();
            decl_message.decl_message_id = decl_message_id;
            return decl_message;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 decl_message_id
        {
            get
            {
                return _decl_message_id;
            }
            set
            {
                if (_decl_message_id != value)
                {
                    Ondecl_message_idChanging(value);
                    ReportPropertyChanging("decl_message_id");
                    _decl_message_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("decl_message_id");
                    Ondecl_message_idChanged();
                }
            }
        }
        private global::System.Int64 _decl_message_id;
        partial void Ondecl_message_idChanging(global::System.Int64 value);
        partial void Ondecl_message_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String send_message_id
        {
            get
            {
                return _send_message_id;
            }
            set
            {
                Onsend_message_idChanging(value);
                ReportPropertyChanging("send_message_id");
                _send_message_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("send_message_id");
                Onsend_message_idChanged();
            }
        }
        private global::System.String _send_message_id;
        partial void Onsend_message_idChanging(global::System.String value);
        partial void Onsend_message_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String out_decl_no
        {
            get
            {
                return _out_decl_no;
            }
            set
            {
                Onout_decl_noChanging(value);
                ReportPropertyChanging("out_decl_no");
                _out_decl_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("out_decl_no");
                Onout_decl_noChanged();
            }
        }
        private global::System.String _out_decl_no;
        partial void Onout_decl_noChanging(global::System.String value);
        partial void Onout_decl_noChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> message_type
        {
            get
            {
                return _message_type;
            }
            set
            {
                Onmessage_typeChanging(value);
                ReportPropertyChanging("message_type");
                _message_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("message_type");
                Onmessage_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _message_type;
        partial void Onmessage_typeChanging(Nullable<global::System.Int32> value);
        partial void Onmessage_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message_detail
        {
            get
            {
                return _message_detail;
            }
            set
            {
                Onmessage_detailChanging(value);
                ReportPropertyChanging("message_detail");
                _message_detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("message_detail");
                Onmessage_detailChanged();
            }
        }
        private global::System.String _message_detail;
        partial void Onmessage_detailChanging(global::System.String value);
        partial void Onmessage_detailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> send_place
        {
            get
            {
                return _send_place;
            }
            set
            {
                Onsend_placeChanging(value);
                ReportPropertyChanging("send_place");
                _send_place = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("send_place");
                Onsend_placeChanged();
            }
        }
        private Nullable<global::System.Int64> _send_place;
        partial void Onsend_placeChanging(Nullable<global::System.Int64> value);
        partial void Onsend_placeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cdiModel", Name="resp_message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resp_message : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 resp_message 对象。
        /// </summary>
        /// <param name="response_message_id">response_message_id 属性的初始值。</param>
        public static resp_message Createresp_message(global::System.Int64 response_message_id)
        {
            resp_message resp_message = new resp_message();
            resp_message.response_message_id = response_message_id;
            return resp_message;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 response_message_id
        {
            get
            {
                return _response_message_id;
            }
            set
            {
                if (_response_message_id != value)
                {
                    Onresponse_message_idChanging(value);
                    ReportPropertyChanging("response_message_id");
                    _response_message_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("response_message_id");
                    Onresponse_message_idChanged();
                }
            }
        }
        private global::System.Int64 _response_message_id;
        partial void Onresponse_message_idChanging(global::System.Int64 value);
        partial void Onresponse_message_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String send_message_id
        {
            get
            {
                return _send_message_id;
            }
            set
            {
                Onsend_message_idChanging(value);
                ReportPropertyChanging("send_message_id");
                _send_message_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("send_message_id");
                Onsend_message_idChanged();
            }
        }
        private global::System.String _send_message_id;
        partial void Onsend_message_idChanging(global::System.String value);
        partial void Onsend_message_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String receive_message_id
        {
            get
            {
                return _receive_message_id;
            }
            set
            {
                Onreceive_message_idChanging(value);
                ReportPropertyChanging("receive_message_id");
                _receive_message_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("receive_message_id");
                Onreceive_message_idChanged();
            }
        }
        private global::System.String _receive_message_id;
        partial void Onreceive_message_idChanging(global::System.String value);
        partial void Onreceive_message_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> message_type
        {
            get
            {
                return _message_type;
            }
            set
            {
                Onmessage_typeChanging(value);
                ReportPropertyChanging("message_type");
                _message_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("message_type");
                Onmessage_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _message_type;
        partial void Onmessage_typeChanging(Nullable<global::System.Int32> value);
        partial void Onmessage_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message_detail
        {
            get
            {
                return _message_detail;
            }
            set
            {
                Onmessage_detailChanging(value);
                ReportPropertyChanging("message_detail");
                _message_detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("message_detail");
                Onmessage_detailChanged();
            }
        }
        private global::System.String _message_detail;
        partial void Onmessage_detailChanging(global::System.String value);
        partial void Onmessage_detailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String out_decl_no
        {
            get
            {
                return _out_decl_no;
            }
            set
            {
                Onout_decl_noChanging(value);
                ReportPropertyChanging("out_decl_no");
                _out_decl_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("out_decl_no");
                Onout_decl_noChanged();
            }
        }
        private global::System.String _out_decl_no;
        partial void Onout_decl_noChanging(global::System.String value);
        partial void Onout_decl_noChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> send_place
        {
            get
            {
                return _send_place;
            }
            set
            {
                Onsend_placeChanging(value);
                ReportPropertyChanging("send_place");
                _send_place = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("send_place");
                Onsend_placeChanged();
            }
        }
        private Nullable<global::System.Int64> _send_place;
        partial void Onsend_placeChanging(Nullable<global::System.Int64> value);
        partial void Onsend_placeChanged();

        #endregion
    
    }

    #endregion
    
}
